apiVersion: v1
kind: Service
metadata:
  name: booking-server-svc
  namespace: room-booking
spec:
  selector:
    app: booking-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
